// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tx.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transaction represents a request or action submitted to the network like transfer assets or perform other operations
// within the blockchain system - THIS MUST MATCH lib.Transaction EXACTLY for signing
type Transaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type: The type of the transaction like 'send' or 'stake'
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"messageType"` // @gotags: json:"messageType"
	// msg: The actual transaction message payload, which is encapsulated in a generic message format
	Msg *anypb.Any `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// signature: The cryptographic signature used to verify the authenticity of the transaction
	Signature *Signature `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// created_height: The height when the transaction was created - allows 'safe pruning'
	CreatedHeight uint64 `protobuf:"varint,4,opt,name=created_height,json=createdHeight,proto3" json:"createdHeight"` // @gotags: json:"createdHeight"
	// time: The timestamp when the transaction was created - used as temporal entropy to prevent hash collisions in txs
	Time uint64 `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	// fee: The fee associated with processing the transaction
	Fee uint64 `protobuf:"varint,6,opt,name=fee,proto3" json:"fee,omitempty"`
	// memo: An optional message or note attached to the transaction
	Memo string `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	// network_id: The identity of the network the transaction is intended for
	NetworkId uint64 `protobuf:"varint,8,opt,name=network_id,json=networkId,proto3" json:"networkID"` // @gotags: json:"networkID"
	// chain_id: The identity of the committee the transaction is intended for
	ChainId       uint64 `protobuf:"varint,9,opt,name=chain_id,json=chainId,proto3" json:"chainID"` // @gotags: json:"chainID"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *Transaction) GetMsg() *anypb.Any {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Transaction) GetCreatedHeight() uint64 {
	if x != nil {
		return x.CreatedHeight
	}
	return 0
}

func (x *Transaction) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Transaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *Transaction) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *Transaction) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// MessageSend is a standard transfer transaction, taking tokens from the sender and transferring
// them to the recipient
type MessageSend struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_address: is the sender of the funds
	FromAddress []byte `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"` // @gotags: json:"fromAddress"
	// to_address: is the recipient of the funds
	ToAddress []byte `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"` // @gotags: json:"toAddress"
	// amount: is the amount of tokens in micro-denomination (uCNPY)
	Amount        uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSend) Reset() {
	*x = MessageSend{}
	mi := &file_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSend) ProtoMessage() {}

func (x *MessageSend) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSend.ProtoReflect.Descriptor instead.
func (*MessageSend) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MessageSend) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}

func (x *MessageSend) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *MessageSend) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// FeeParams is the parameter space that defines various amounts for transaction fees
type FeeParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// send_fee: is the fee amount (in uCNPY) for Message Send
	SendFee       uint64 `protobuf:"varint,1,opt,name=send_fee,json=sendFee,proto3" json:"sendFee"` // @gotags: json:"sendFee"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeParams) Reset() {
	*x = FeeParams{}
	mi := &file_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeParams) ProtoMessage() {}

func (x *FeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeParams.ProtoReflect.Descriptor instead.
func (*FeeParams) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{2}
}

func (x *FeeParams) GetSendFee() uint64 {
	if x != nil {
		return x.SendFee
	}
	return 0
}

// A Signature is a digital signature is a cryptographic "fingerprint" created with a private key,
// allowing others to verify the authenticity and integrity of a message using the corresponding public key
type Signature struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// public_key: is a cryptographic code shared openly, used to verify digital signatures
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"publicKey"` // @gotags: json:"publicKey"
	// signature: the bytes of the signature output from a private key which may be verified with the message and public
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{3}
}

func (x *Signature) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// MessagePriceSignal is a custom transaction for posting commodity price signals
type MessagePriceSignal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oracle_address: the address of the oracle posting the signal
	OracleAddress []byte `protobuf:"bytes,1,opt,name=oracle_address,json=oracleAddress,proto3" json:"oracleAddress"` // @gotags: json:"oracleAddress"
	// asset: the commodity ticker e.g. "WTI", "BTC", "ETH"
	Asset string `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	// price: the price in USD cents (e.g. 7245 = $72.45)
	Price uint64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// sentiment: "bullish", "bearish", or "neutral"
	Sentiment string `protobuf:"bytes,4,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	// confidence: confidence level 1-100
	Confidence uint64 `protobuf:"varint,5,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// source: data source label e.g. "mexc_perps"
	Source        string `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePriceSignal) Reset() {
	*x = MessagePriceSignal{}
	mi := &file_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePriceSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePriceSignal) ProtoMessage() {}

func (x *MessagePriceSignal) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePriceSignal.ProtoReflect.Descriptor instead.
func (*MessagePriceSignal) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MessagePriceSignal) GetOracleAddress() []byte {
	if x != nil {
		return x.OracleAddress
	}
	return nil
}

func (x *MessagePriceSignal) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *MessagePriceSignal) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MessagePriceSignal) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

func (x *MessagePriceSignal) GetConfidence() uint64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MessagePriceSignal) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// MessageSubmitPrice posts a WTI spot price from the authorized oracle
type MessageSubmitPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OracleAddress []byte                 `protobuf:"bytes,1,opt,name=oracle_address,json=oracleAddress,proto3" json:"oracleAddress"` // @gotags: json:"oracleAddress"
	PriceUsd      uint64                 `protobuf:"varint,2,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`               // price in USD cents (7245 = $72.45)
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSubmitPrice) Reset() {
	*x = MessageSubmitPrice{}
	mi := &file_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSubmitPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSubmitPrice) ProtoMessage() {}

func (x *MessageSubmitPrice) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSubmitPrice.ProtoReflect.Descriptor instead.
func (*MessageSubmitPrice) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MessageSubmitPrice) GetOracleAddress() []byte {
	if x != nil {
		return x.OracleAddress
	}
	return nil
}

func (x *MessageSubmitPrice) GetPriceUsd() uint64 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

func (x *MessageSubmitPrice) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageSubmitPrice) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// MessageSubmitIndicator posts a technical indicator snapshot
type MessageSubmitIndicator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OracleAddress []byte                 `protobuf:"bytes,1,opt,name=oracle_address,json=oracleAddress,proto3" json:"oracleAddress"` // @gotags: json:"oracleAddress"
	Timeframe     string                 `protobuf:"bytes,2,opt,name=timeframe,proto3" json:"timeframe,omitempty"`                              // "5m","15m","1h","4h"
	Rsi           uint64                 `protobuf:"varint,3,opt,name=rsi,proto3" json:"rsi,omitempty"`                                         // basis points, 6532 = 65.32
	Macd          uint64                 `protobuf:"varint,4,opt,name=macd,proto3" json:"macd,omitempty"`
	MacdSignal    uint64                 `protobuf:"varint,5,opt,name=macd_signal,json=macdSignal,proto3" json:"macd_signal,omitempty"`
	BbUpper       uint64                 `protobuf:"varint,6,opt,name=bb_upper,json=bbUpper,proto3" json:"bb_upper,omitempty"`
	BbLower       uint64                 `protobuf:"varint,7,opt,name=bb_lower,json=bbLower,proto3" json:"bb_lower,omitempty"`
	Ema20         uint64                 `protobuf:"varint,8,opt,name=ema20,proto3" json:"ema20,omitempty"`
	Ema25         uint64                 `protobuf:"varint,9,opt,name=ema25,proto3" json:"ema25,omitempty"`
	Timestamp     int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSubmitIndicator) Reset() {
	*x = MessageSubmitIndicator{}
	mi := &file_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageSubmitIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageSubmitIndicator) ProtoMessage() {}

func (x *MessageSubmitIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageSubmitIndicator.ProtoReflect.Descriptor instead.
func (*MessageSubmitIndicator) Descriptor() ([]byte, []int) {
	return file_tx_proto_rawDescGZIP(), []int{6}
}

func (x *MessageSubmitIndicator) GetOracleAddress() []byte {
	if x != nil {
		return x.OracleAddress
	}
	return nil
}

func (x *MessageSubmitIndicator) GetTimeframe() string {
	if x != nil {
		return x.Timeframe
	}
	return ""
}

func (x *MessageSubmitIndicator) GetRsi() uint64 {
	if x != nil {
		return x.Rsi
	}
	return 0
}

func (x *MessageSubmitIndicator) GetMacd() uint64 {
	if x != nil {
		return x.Macd
	}
	return 0
}

func (x *MessageSubmitIndicator) GetMacdSignal() uint64 {
	if x != nil {
		return x.MacdSignal
	}
	return 0
}

func (x *MessageSubmitIndicator) GetBbUpper() uint64 {
	if x != nil {
		return x.BbUpper
	}
	return 0
}

func (x *MessageSubmitIndicator) GetBbLower() uint64 {
	if x != nil {
		return x.BbLower
	}
	return 0
}

func (x *MessageSubmitIndicator) GetEma20() uint64 {
	if x != nil {
		return x.Ema20
	}
	return 0
}

func (x *MessageSubmitIndicator) GetEma25() uint64 {
	if x != nil {
		return x.Ema25
	}
	return 0
}

func (x *MessageSubmitIndicator) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_tx_proto protoreflect.FileDescriptor

const file_tx_proto_rawDesc = "" +
	"\n" +
	"\btx.proto\x12\x05types\x1a\x19google/protobuf/any.proto\"\xa3\x02\n" +
	"\vTransaction\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12&\n" +
	"\x03msg\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x03msg\x12.\n" +
	"\tsignature\x18\x03 \x01(\v2\x10.types.SignatureR\tsignature\x12%\n" +
	"\x0ecreated_height\x18\x04 \x01(\x04R\rcreatedHeight\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x04R\x04time\x12\x10\n" +
	"\x03fee\x18\x06 \x01(\x04R\x03fee\x12\x12\n" +
	"\x04memo\x18\a \x01(\tR\x04memo\x12\x1d\n" +
	"\n" +
	"network_id\x18\b \x01(\x04R\tnetworkId\x12\x19\n" +
	"\bchain_id\x18\t \x01(\x04R\achainId\"g\n" +
	"\vMessageSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\fR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\fR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"&\n" +
	"\tFeeParams\x12\x19\n" +
	"\bsend_fee\x18\x01 \x01(\x04R\asendFee\"H\n" +
	"\tSignature\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xbd\x01\n" +
	"\x12MessagePriceSignal\x12%\n" +
	"\x0eoracle_address\x18\x01 \x01(\fR\roracleAddress\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x04R\x05price\x12\x1c\n" +
	"\tsentiment\x18\x04 \x01(\tR\tsentiment\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x04R\n" +
	"confidence\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\"\x8e\x01\n" +
	"\x12MessageSubmitPrice\x12%\n" +
	"\x0eoracle_address\x18\x01 \x01(\fR\roracleAddress\x12\x1b\n" +
	"\tprice_usd\x18\x02 \x01(\x04R\bpriceUsd\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\xa4\x02\n" +
	"\x16MessageSubmitIndicator\x12%\n" +
	"\x0eoracle_address\x18\x01 \x01(\fR\roracleAddress\x12\x1c\n" +
	"\ttimeframe\x18\x02 \x01(\tR\ttimeframe\x12\x10\n" +
	"\x03rsi\x18\x03 \x01(\x04R\x03rsi\x12\x12\n" +
	"\x04macd\x18\x04 \x01(\x04R\x04macd\x12\x1f\n" +
	"\vmacd_signal\x18\x05 \x01(\x04R\n" +
	"macdSignal\x12\x19\n" +
	"\bbb_upper\x18\x06 \x01(\x04R\abbUpper\x12\x19\n" +
	"\bbb_lower\x18\a \x01(\x04R\abbLower\x12\x14\n" +
	"\x05ema20\x18\b \x01(\x04R\x05ema20\x12\x14\n" +
	"\x05ema25\x18\t \x01(\x04R\x05ema25\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestampB.Z,github.com/canopy-network/go-plugin/contractb\x06proto3"

var (
	file_tx_proto_rawDescOnce sync.Once
	file_tx_proto_rawDescData []byte
)

func file_tx_proto_rawDescGZIP() []byte {
	file_tx_proto_rawDescOnce.Do(func() {
		file_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)))
	})
	return file_tx_proto_rawDescData
}

var file_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_tx_proto_goTypes = []any{
	(*Transaction)(nil),            // 0: types.Transaction
	(*MessageSend)(nil),            // 1: types.MessageSend
	(*FeeParams)(nil),              // 2: types.FeeParams
	(*Signature)(nil),              // 3: types.Signature
	(*MessagePriceSignal)(nil),     // 4: types.MessagePriceSignal
	(*MessageSubmitPrice)(nil),     // 5: types.MessageSubmitPrice
	(*MessageSubmitIndicator)(nil), // 6: types.MessageSubmitIndicator
	(*anypb.Any)(nil),              // 7: google.protobuf.Any
}
var file_tx_proto_depIdxs = []int32{
	7, // 0: types.Transaction.msg:type_name -> google.protobuf.Any
	3, // 1: types.Transaction.signature:type_name -> types.Signature
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tx_proto_init() }
func file_tx_proto_init() {
	if File_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_proto_rawDesc), len(file_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tx_proto_goTypes,
		DependencyIndexes: file_tx_proto_depIdxs,
		MessageInfos:      file_tx_proto_msgTypes,
	}.Build()
	File_tx_proto = out.File
	file_tx_proto_goTypes = nil
	file_tx_proto_depIdxs = nil
}
